spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=MySQL
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        ddl-auto: create
logging:
  level:
    org:
      hibernate:
        SQL: debug
        type.descriptor.sql: trace
        orm.jdbc.bind: trace
auth:
  jwt:
    issuer: moomoo.onboarding
    secret: fd01c9a6750d9c51af495858682be0892caebc79f7bdf7d274afdb7645d6a14a
    accessTokenExpirationHour: 2